### ISSUE TITLE
Weird SoundProcesses.step / Txn.findCurrent glitch

### ISSUE THREAD

**Issue by Sciss** [Sciss/SoundProcesses#85]
In GitLab by @Sciss on Nov 15, 2020, 17:27

```
[ERROR] [11/15/2020 16:53:52.556] [fscape-akka.actor.internal-dispatcher-2] [akka://fscape/user/$a] Cannot nest transactions
java.lang.IllegalStateException: Cannot nest transactions
	at de.sciss.synth.proc.SoundProcesses$.step(SoundProcesses.scala:86)
	at de.sciss.synth.proc.impl.FScapeRunnerImpl$Impl$progress$.report(FScapeRunnerImpl.scala:102)
	at de.sciss.synth.proc.impl.FScapeRunnerImpl$Impl$progress$.push(FScapeRunnerImpl.scala:81)
	at de.sciss.synth.proc.impl.FScapeRunnerImpl$Impl.$anonfun$run$1(FScapeRunnerImpl.scala:138)
	at de.sciss.synth.proc.impl.FScapeRunnerImpl$Impl.$anonfun$run$1$adapted(FScapeRunnerImpl.scala:137)
	at de.sciss.fscape.stream.Control$AbstractImpl.de$sciss$fscape$stream$Control$AbstractImpl$$actSetProgress(Control.scala:275)
	at de.sciss.fscape.stream.Control$AbstractImpl$ActorImpl$$anonfun$receive$1.applyOrElse(Control.scala:382)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at de.sciss.fscape.stream.Control$AbstractImpl$ActorImpl.aroundReceive(Control.scala:380)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```
I don't know how it is possible that we see an instance here? Unless the thread was reused and the transaction didn't clean up its local thread state?

**Comment by Sciss** [comment]
In GitLab by @Sciss on Nov 15, 2020, 18:45

heisenbug'ish :-/

**Comment by Sciss** [comment]
In GitLab by @Sciss on Nov 26, 2020, 16:21

Again with current code base:

```
[2020-11-26 16:14:38.319] [warn] 'proc' SoundProcesses.step. Existing transaction Some(InTxnImpl@f9f9d8(Detached, slot=-594, subsumptionAllowed=true, priority=-366002941, readCount=0, bargeCount=0, writeCount=0, readVersion=0x91, cumulativeBlockingNanos=0, commitBarrier=null))
[ERROR] [11/26/2020 16:14:38.326] [fscape-akka.actor.internal-dispatcher-3] [akka://fscape/user/$f] Cannot nest transactions
java.lang.IllegalStateException: Cannot nest transactions
	at de.sciss.proc.SoundProcesses$.step(SoundProcesses.scala:67)
	at de.sciss.proc.impl.FScapeRunnerImpl$Impl$progress$.report(FScapeRunnerImpl.scala:102)
	at de.sciss.proc.impl.FScapeRunnerImpl$Impl$progress$.push(FScapeRunnerImpl.scala:81)
	at de.sciss.proc.impl.FScapeRunnerImpl$Impl.$anonfun$run$1(FScapeRunnerImpl.scala:138)
	at de.sciss.proc.impl.FScapeRunnerImpl$Impl.$anonfun$run$1$adapted(FScapeRunnerImpl.scala:137)
	at de.sciss.fscape.stream.Control$AbstractImpl.de$sciss$fscape$stream$Control$AbstractImpl$$actSetProgress(Control.scala:275)
	at de.sciss.fscape.stream.Control$AbstractImpl$ActorImpl$$anonfun$receive$1.applyOrElse(Control.scala:382)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at de.sciss.fscape.stream.Control$AbstractImpl$ActorImpl.aroundReceive(Control.scala:380)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

What I think is happening: We have this in rendering:

```scala
      def push(value: Double): Unit = {
        guiValue = value
        val now = System.currentTimeMillis()
        if (now - lastReported > 150) {
          timerRef.single.swap(None).foreach(_.cancel())
          report()
       ...
```
Notice the `.single` access. That might create a short lived transaction that is on the same thread as the call to `report()` (which calls `SoundProcesses.step`). Looking at the new print-out, that transaction says `Detached`, and `subsumptionAllowed=true`. I suppose, we can identify this and avoid the refusal in SP.step.

**Comment by Sciss** [comment]
In GitLab by @Sciss on Nov 28, 2020, 13:45

c.f. https://github.com/scala-stm/scala-stm/issues/14
